# Generated by Django 5.1 on 2024-10-30 17:03

import uuid
import videokyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocvecLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=255)),
                ('submitted_image', models.FileField(blank=True, null=True, upload_to=videokyc.models.bank_client_directory)),
                ('video_image', models.FileField(blank=True, null=True, upload_to=videokyc.models.bank_client_directory)),
                ('verification_status', models.CharField(default='PENDING', max_length=20)),
                ('email_status', models.CharField(default='PENDING', max_length=20)),
                ('api_key', models.CharField(max_length=50)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('initiator', models.JSONField(blank=True, default=dict, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=20, null=True)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('othernames', models.CharField(blank=True, max_length=200, null=True)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('link_sent_time', models.DateTimeField(auto_now=True)),
                ('video_verification_start_time', models.CharField(blank=True, null=True)),
                ('verification_completed_time', models.DateTimeField(auto_now=True, null=True)),
                ('verification_duration', models.DateTimeField(auto_now=True, null=True)),
                ('verification_completed', models.BooleanField(default=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('verification_reason', models.CharField(blank=True, null=True)),
                ('client_id', models.CharField()),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('liveliness_detection', models.JSONField(blank=True, null=True)),
                ('consent_sorted', models.BooleanField(default=False)),
                ('sim_swap_details', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('STANDARD', 'Standard')], max_length=50)),
                ('description', models.TextField(null=True)),
                ('ofac_verification', models.JSONField(blank=True, null=True)),
                ('video_verification_details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=255)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
