# Generated by Django 5.1 on 2024-09-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0002_alter_imagecomparison_initiator'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomparison',
            name='client_id',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
