# Generated by Django 5.1 on 2024-09-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0003_imagecomparison_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomparison',
            name='verification_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagecomparison',
            name='verification_completed_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagecomparison',
            name='video_verification_start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
