# Generated by Django 5.1 on 2024-09-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0006_imagecomparison_verification_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomparison',
            name='device_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
