# Generated by Django 5.1 on 2024-09-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0007_imagecomparison_device_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomparison',
            name='liveliness_detection',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
