# Generated by Django 5.1 on 2024-09-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0008_imagecomparison_liveliness_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomparison',
            name='consent_sorted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
