# Generated by Django 5.1 on 2024-09-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0009_imagecomparison_consent_sorted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomparison',
            name='consent_sorted',
            field=models.BooleanField(default=False),
        ),
    ]
