# Generated by Django 5.1 on 2024-09-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0010_alter_imagecomparison_consent_sorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomparison',
            name='sim_swap_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
