# Generated by Django 5.1 on 2024-09-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0011_imagecomparison_sim_swap_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomparison',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imagecomparison',
            name='type',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('STANDARD_VERIFICATION', 'Standard Verification')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
