# Generated by Django 5.1 on 2024-09-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0013_imagecomparison_ofac_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomparison',
            name='video_verification_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
