# Generated by Django 5.1 on 2024-09-20 04:10

import videokyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0015_imagecomparison_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomparison',
            name='video',
            field=models.FileField(default='', upload_to=videokyc.models.bank_client_directory),
            preserve_default=False,
        ),
    ]
