# Generated by Django 5.1 on 2024-10-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0018_docveclink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomparison',
            name='type',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('STANDARD', 'Standard')], max_length=50),
        ),
    ]
