# Generated by Django 5.1 on 2024-10-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0019_alter_imagecomparison_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomparison',
            name='video_verification_start_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
