# Generated by Django 5.1 on 2024-10-07 17:07

import videokyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videokyc', '0020_alter_imagecomparison_video_verification_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomparison',
            name='video_image',
            field=models.FileField(blank=True, null=True, upload_to=videokyc.models.bank_client_directory),
        ),
    ]
