# Generated by Django 5.1 on 2024-11-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='account',
            new_name='business',
        ),
    ]
