# Generated by Django 5.1 on 2024-11-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_teammember_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='status',
        ),
    ]
