# Generated by Django 5.1 on 2024-11-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_primary_account',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
