# Generated by Django 5.1 on 2024-09-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='core_business_id',
            new_name='client_id',
        ),
    ]
