# Generated by Django 5.1 on 2024-09-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0002_rename_core_business_id_account_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikeys',
            old_name='business',
            new_name='client',
        ),
    ]
