# Generated by Django 5.1 on 2024-09-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0003_rename_business_apikeys_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
