# Generated by Django 5.1 on 2024-09-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0004_remove_account_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
